"use client";
import { useMemo, useState } from "react";
import { SettingsDrawer } from "@/app/(dashboard)/parametres/settings-drawer";
import { ActionIcon } from "@/app/action-icon";
import { deleteMontageTask, updateMontageTaskStatus } from "./actions";
import { taskStatuses } from "./options";
import type { MontageTask } from "./types";
import { MontageForm } from "./montage-form";
export function MontageManager({ initialTasks, editors, clients, canManage }: { initialTasks: MontageTask[]; editors:{id:number;name:string;phone:string|null}[]; clients:{id:number;name:string}[]; canManage: boolean }) {
  const [tasks,setTasks]=useState(initialTasks); const [query,setQuery]=useState(""); const [editorFilter,setEditorFilter]=useState("all"); const [statusFilter,setStatusFilter]=useState("all"); const [drawer,setDrawer]=useState<MontageTask|"new"|null>(null); const [notice,setNotice]=useState("");
  const filtered=useMemo(()=>tasks.filter(t=>(!query.trim() || `${t.title} ${t.clientName??""} ${t.editorName}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())) && (editorFilter==="all"||String(t.editorId)===editorFilter) && (statusFilter==="all"||t.status===statusFilter)),[tasks,query,editorFilter,statusFilter]);
  function saved(row:MontageTask){setTasks(current=>current.some(t=>t.id===row.id)?current.map(t=>t.id===row.id?row:t):[row,...current]);setDrawer(null);setNotice("Tâche enregistrée.");}
  async function changeStatus(task:MontageTask,status:string){const old=task.status;setTasks(c=>c.map(t=>t.id===task.id?{...t,status}:t));const result=await updateMontageTaskStatus(task.id,status);if(result.error){setTasks(c=>c.map(t=>t.id===task.id?{...t,status:old}:t));setNotice(result.error);}}
  async function remove(task:MontageTask){if(!confirm(`Supprimer « ${task.title} » ?`))return;const previous=tasks;setTasks(c=>c.filter(t=>t.id!==task.id));const result=await deleteMontageTask(task.id);if(result.error){setTasks(previous);setNotice(result.error);}else setNotice("Tâche supprimée.");}
  return <div className="max-w-7xl"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-slate-500 uppercase">Production</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Gestion du montage</h1><p className="mt-2 text-sm text-slate-500">{canManage ? "Un suivi simple des livrables de l’équipe." : "La liste complète des tâches de montage."}</p></div>{canManage&&<button className="btn-primary" onClick={()=>setDrawer("new")}>+ Nouvelle tâche</button>}</div>
    <div className="mb-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-[1fr_200px_180px]"><input className="field" placeholder="Rechercher une tâche, un client…" value={query} onChange={e=>setQuery(e.target.value)} /><select className="field" value={editorFilter} onChange={e=>setEditorFilter(e.target.value)}><option value="all">Tous les monteurs</option>{editors.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select className="field" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Tous les statuts</option>{taskStatuses.map(s=><option key={s}>{s}</option>)}</select></div>
    {notice&&<p className="mb-4 text-sm font-medium text-indigo-700">{notice}</p>}
    <div className="grid gap-4 xl:grid-cols-3">{taskStatuses.map(status=><section key={status} className="min-h-80 rounded-xl border border-slate-200 bg-white p-3"><div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="text-sm font-bold text-slate-800">{status}</h2><span className="text-xs font-semibold text-slate-400">{filtered.filter(t=>t.status===status).length}</span></div><div className="space-y-2">{filtered.filter(t=>t.status===status).map(task=><article key={task.id} className="rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-bold leading-snug text-slate-900">{task.title}</h3>{canManage&&<div className="flex shrink-0 gap-1"><button className="icon-button" title="Modifier" onClick={()=>setDrawer(task)}><ActionIcon name="edit"/></button><button className="icon-button text-red-500" title="Supprimer" onClick={()=>remove(task)}><ActionIcon name="delete"/></button></div>}</div>{task.clientName&&<p className="mt-1 text-xs font-semibold text-slate-600">{task.clientName}</p>}<div className="mt-2 flex items-center justify-between gap-2 text-xs text-slate-500"><span>{task.editorName}</span>{task.dueDate&&<span>{new Intl.DateTimeFormat("fr-MA").format(new Date(`${task.dueDate}T12:00:00`))}</span>}</div>{task.editorPhone&&canManage&&<a className="mt-2 inline-flex text-xs font-semibold text-emerald-700 hover:underline" href={`https://wa.me/${task.editorPhone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer"><ActionIcon name="whatsapp"/> <span className="ml-1">WhatsApp</span></a>}{task.description&&<p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{task.description}</p>}<select className="field mt-2 py-1.5 text-xs" value={task.status} onChange={e=>changeStatus(task,e.target.value)} aria-label="Changer le statut">{taskStatuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</div>{filtered.filter(t=>t.status===status).length===0&&<p className="py-10 text-center text-sm text-slate-400">Aucune tâche</p>}</section>)}</div>
    {drawer&&canManage&&<SettingsDrawer title={drawer==="new"?"Nouvelle tâche":"Modifier la tâche"} onClose={()=>setDrawer(null)} wide><MontageForm editors={editors} clients={clients} record={drawer==="new"?undefined:drawer} onSaved={saved}/></SettingsDrawer>}
  </div>;
}
