ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "editorId" INTEGER;
CREATE INDEX IF NOT EXISTS "User_editorId_idx" ON "User"("editorId");
ALTER TABLE "User" ADD CONSTRAINT "User_editorId_fkey" FOREIGN KEY ("editorId") REFERENCES "Editor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
